# DB setting
spring:
  datasource:
    url: jdbc:mysql://todomatedb:3306/todomate?useUnicode=true&characterEncoding=UTF-8&characterSetResult=UTF-8&useSSL=true
    username: root
    password: 1234

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security.web: trace  # 시큐리티 관련 로그 남기기

server:
  port: 8099
  servlet:
    session:
      tracking-modes: cookie

jwt:
  key: SGVsbG9Kc29uV2ViVG9rZW5BdXRoZW50aWNhdGlvbktleVdpdGhTcHJpbmdCb29rUHJvamVjdFNlY3JldEtleQ
